"""delete status

Revision ID: 980546e58c42
Revises: 30d11adbd3c5
Create Date: 2025-01-07 00:42:58.816179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980546e58c42'
down_revision: Union[str, None] = '30d11adbd3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
